- name: "Check if key already exist locally"
  local_action: stat path={{playbook_dir}}/key
  register: OwnCloudPriKeyExist

- name: "Create a new private key"
  ec2_key:
    state: "{{aws_state}}"
    name: owncloud
    force: false
    region: "{{aws_region}}"
  register: OwnCloudPriKey
  when: OwnCloudPriKeyExist|failed

- debug:
    msg: "{{OwnCloudPriKey}}"
  when: (run_in_debug == true) and (OwnCloudPriKeyExist|failed)

- name: "Save Key"
  set_fact:
    OwnCloudPriKeyContent: "{{ OwnCloudPriKey.key.private_key }}"
  ignore_errors: true
  register: OwnCloudPriKeySaved
  when: OwnCloudPriKeyExist|failed


- name: "Rollback private key"
  ec2_key:
    state: absent
    name: owncloud
    force: true
    region: "{{aws_region}}"
  when: (OwnCloudPriKeySaved|failed) and (OwnCloudPriKeyExist|failed)

- local_action: copy content={{ OwnCloudPriKeyContent }} dest={{playbook_dir}}/key
  when: (OwnCloudPriKeySaved|success) and (OwnCloudPriKeyExist|failed)
