---
- name: "Create a Security Group"
  ec2_group:
    name: "External SSH Access"
    description: "External SSH Access"
    vpc_id: "{{ OwnCloudVpcId }}"
    region: "{{ aws_region }}"
    rules:
      - proto: "tcp"
        from_port: "22"
        to_port: "22"
        cidr_ip: "0.0.0.0/0"
      - proto: "tcp"
        from_port: "80"
        to_port: "80"
        cidr_ip: "0.0.0.0/0"
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        cidr_ip: "0.0.0.0/0"
  register: OwnCloudVpcSg

- debug:
    msg: "{{OwnCloudVpcSg}}"
  when: run_in_debug == true

- name: "Save Security Group ID"
  set_fact:
    OwnCloudVpcId: "{{ OwnCloudVpcSg.group_id }}"
